# Jekyll configuration

name: BWY-Dev
description: Welcome to BWY-DevÔºÅ

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/bwy-dev

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 8

highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
