# Jekyll configuration

name: BWY-Development
description: Programming/Game-Dev Blog.
disqus: bwy-dev
# url is currently only used only for the RSS feed in feed.xml
url: https://bwy-dev.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 8

markdown: redcarpet 
highlighter: pygments 
redcarpet:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

exclude: ['README.md', 'LICENSE', "*.bak"]
